### ISSUE TITLE
cannot process all files

### ISSUE THREAD

**Issue by lingjzhu** [asuni/wavelet_prosody_toolkit#12]
Hi I am using this toolkit to analyze a speech corpus. The software worked amazingly well on individual files. However, whenever I tried to click the "process all files" button, I got the following error. I tired this with the samples folder and my own data and the errors were always the same.

```/mnt/exp/wavelet_prosody_toolkit-master/wavelet_prosody_toolkit/wavelet_gui.py:1089: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configuration = apply_configuration(configuration, defaultdict(lambda: False, yaml.load(f)))
20
Traceback (most recent call last):
  File "/mnt/exp/wavelet_prosody_toolkit-master/wavelet_prosody_toolkit/wavelet_gui.py", line 684, in processAll
    feats.append("%0.5f" % p[1])
IndexError: string index out of range
Aborted (core dumped)
```

If you happen to have some time, could you give me some hints as to  how to solve this problem? Thanks very much. My Python version is 3.6 and everything works well except this "process all files" function.

**Comment by lingjzhu** [comment]
OK. I fixed this bug by looking into the source code. I modified line 682 to 684 in wavelet_gui.py and the program now works well. The original code in line 682 use np.array_str, so p is not an array but a string and cannot be indexed. I also change np.array_str to np.array so that p is a float rather than a string.

The original code is:
```
            self.prominences = np.array_str(self.prominences[:, 1], precision=3)
            for p in self.prominences:
                feats.append("%0.5f" % p[1])
```

My modification is:
```
            self.prominences = np.array(self.prominences[:, 1])
            for p in self.prominences:
                feats.append("%0.5f" % p)
```

**Comment by seblemaguer** [comment]
Hello,

thanks for the issue, on my side your patch is crashing. I am on python 3.7 so I think it will need a more refined solution. I will work on this.
