### ISSUE TITLE
Package installation

### ISSUE THREAD

**Issue by niuniuniufangfang** [asuni/wavelet_prosody_toolkit#28]
Hello, I want to install this tool and follow your installation instructions. But I don’t understand what you mean by "To be able to run the application globally, the following line should be added to your shell profile file (~/.bashrc or ~/.profile in general): ". I want to know if there is one less sentence written here  or which line should be added to my shell profile? Could u help me? Thanks!
[question.docx](https://github.com/asuni/wavelet_prosody_toolkit/files/5046762/question.docx)

**Comment by seblemaguer** [comment]
Some lines were missing in the INSTALL.rst files. You now have all the instructions.

**Comment by niuniuniufangfang** [comment]
wow! Thank u so much! 
I have downloaded the transcriptions augmented with prosodic labels at https://www.mv.helsinki.ﬁ/home/asuni/sp2020/ ,  but I am so sad that the file is corrupted. Could you send a copy to my mailbox (652074311@qq.com) If you happen to have some time? Thank u !

**Comment by seblemaguer** [comment]
Sorry but I don't have access to this file. I am not sure that this repository is the best neither to ask for it. I suggest you write an email to the authors of the article directly. I close this issue as the main problem seems to be solved

**Comment by niuniuniufangfang** [comment]
Okey, I got it . Thank u so much !
